### PR TITLE
repeated :clojurescript? in project.clj

### PR DESCRIPTION
**Pull request by stumitchell**
Im not sure why but my lein throws an error because of this

### CODE REVIEW

**Comment by w01fe** [comment]
Thanks!  Just so you know, this library isn't currently in active development -- we'd recommend checking out ClojureScript's new built-in support (https://github.com/clojure/clojurescript/blob/master/src/cljs/cljs/test.cljs) or perhaps https://github.com/cemerick/clojurescript.test

**Comment by stumitchell** [comment]
cool but we still use it as it has async tests while test.cljs doesn't yet

Stu

On Thu, Mar 19, 2015 at 11:02 AM, Jason Wolfe <notifications@github.com>
wrote:

> Thanks! Just so you know, this library isn't currently in active
> development -- we'd recommend checking out ClojureScript's new built-in
> support (
> https://github.com/clojure/clojurescript/blob/master/src/cljs/cljs/test.cljs)
> or perhaps https://github.com/cemerick/clojurescript.test
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Prismatic/cljs-test/pull/8#issuecomment-83200793>.
>



-- 
Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by stumitchell** [comment]
Oic they added async testing in feb

**Comment by w01fe** [comment]
Cool, thanks.  I'm happy to push out a new release with this change if that would be helpful to you.

**Comment by stumitchell** [comment]
don't worry about it as the change doesn't do anything anyway I just wasn't getting it to compile on my machine (for tests), strange as travis builds it ok.

**Pull request merged**
